# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F1_rVPIjjLU3_NR5GV7JAotiRqjY7fFX
"""

from fastapi import FastAPI, UploadFile, File, Form
import google.generativeai as genai
import PIL.Image
import time
import os
import shutil

app = FastAPI()

# ==============================================================================
# كودك الأصلي (كما هو تماماً دون أي تعديل في المنطق)
# ==============================================================================

# 1. إعدادات المشروع
MY_API_KEY = os.environ.get("GOOGLE_API_KEY")

MODEL_NAME = "gemini-2.5-flash"

genai.configure(api_key=MY_API_KEY)

class GeminiChatBot:
    def __init__(self):
        # تهيئة الموديل
        self.model = genai.GenerativeModel(MODEL_NAME)
        # بدء جلسة محادثة فارغة (لحفظ التاريخ)
        self.chat_session = self.model.start_chat(history=[])
        print(f"🤖 تم تشغيل البوت باستخدام موديل: {MODEL_NAME}")

    def upload_audio(self, audio_path):
        """دالة مساعدة لرفع الملفات الصوتية وانتظار معالجتها"""
        if not os.path.exists(audio_path):
            return None

        print(f"🎙️ جاري رفع ومعالجة الملف الصوتي: {audio_path}...")
        audio_file = genai.upload_file(path=audio_path)

        # حلقة انتظار حتى تنتهي جوجل من معالجة الملف
        while audio_file.state.name == "PROCESSING":
            time.sleep(1)
            audio_file = genai.get_file(audio_file.name)

        if audio_file.state.name == "FAILED":
            print("❌ فشل في معالجة الملف الصوتي")
            return None

        print("✅ الملف الصوتي جاهز.")
        return audio_file

    def send_message(self, text=None, image_path=None, audio_path=None):
        """
        الدالة الرئيسية التي تستقبل أي نوع من المدخلات وترد عليها
        """
        input_parts = []

        # 1. تجهيز النص
        if text:
            input_parts.append(text)

        # 2. تجهيز الصورة (إن وجدت)
        if image_path:
            try:
                img = PIL.Image.open(image_path)
                input_parts.append(img)
                print("📷 تم إرفاق صورة.")
            except Exception as e:
                return f"❌ خطأ في الصورة: {e}"

        # 3. تجهيز الصوت (إن وجد)
        if audio_path:
            audio_file = self.upload_audio(audio_path)
            if audio_file:
                input_parts.append(audio_file)
            else:
                return "❌ تعذر رفع الملف الصوتي."

        # إذا لم يكن هناك مدخلات
        if not input_parts:
            return "⚠️ لا يوجد مدخلات للإرسال!"

        # 4. الإرسال للموديل والحصول على الرد
        try:
            # نستخدم chat_session لإرسال الرسالة وحفظ السياق
            response = self.chat_session.send_message(input_parts)
            return response.text
        except Exception as e:
            return f"❌ خطأ في النظام: {e}"

    def get_history(self):
        """لعرض تاريخ المحادثة بالكامل"""
        return self.chat_session.history

# ==============================================================================
# نهاية كودك الأصلي
# ==============================================================================

# إنشاء نسخة واحدة من البوت لتعمل على السيرفر
bot_instance = GeminiChatBot()

@app.get("/")
def home():
    return {"message": "Gemini 2.5 Flash API is Running"}

@app.post("/chat")
async def chat_endpoint(
    text: str = Form(None),
    image: UploadFile = File(None),
    audio: UploadFile = File(None)
):
    """
    نقطة الاتصال (API Endpoint)
    تستقبل النص والصورة والصوت، وتحفظ الملفات مؤقتاً لتمريرها لكودك
    """
    temp_image_path = None
    temp_audio_path = None

    try:
        # حفظ الصورة مؤقتاً إذا وجدت (لأن كودك يطلب مسار ملف)
        if image:
            temp_image_path = f"temp_{image.filename}"
            with open(temp_image_path, "wb") as buffer:
                shutil.copyfileobj(image.file, buffer)

        # حفظ الصوت مؤقتاً إذا وجد
        if audio:
            temp_audio_path = f"temp_{audio.filename}"
            with open(temp_audio_path, "wb") as buffer:
                shutil.copyfileobj(audio.file, buffer)

        # استدعاء دالتك الأصلية بنفس طريقتك
        response_text = bot_instance.send_message(
            text=text,
            image_path=temp_image_path,
            audio_path=temp_audio_path
        )

        return {"response": response_text}

    finally:
        # تنظيف الملفات المؤقتة بعد الرد لعدم ملء السيرفر
        if temp_image_path and os.path.exists(temp_image_path):
            os.remove(temp_image_path)
        if temp_audio_path and os.path.exists(temp_audio_path):
            os.remove(temp_audio_path)

# لتشغيل السيرفر محلياً: uvicorn main:app --reloadظط

